disabled_rules: 
  - identifier_name
  - nesting
  - function_parameter_count
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - multiline_arguments_brackets
included: # paths to include during linting. `--path` is ignored if present.
  - StoneLifting
  - StoneLiftingTests
  - StoneLiftingUITests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning

force_try:
  severity: warning

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

large_tuple:
   - 3
   - 4
   
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4
  max_length:
    warning: 30
    error: 35
  excluded: iPhone # excluded via string
  
# line length rules can set warnings/errors for min_length and max_length
line_length:
  warning: 175
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

multiline_arguments_brackets: error

reporter: "xcode"
